train:
    _target_: cropcon.engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
        - _target_: cropcon.engine.data_preprocessor.ResizeToEncoder
        - _target_: cropcon.engine.data_preprocessor.BandFilter
        - _target_: cropcon.engine.data_preprocessor.NormalizeMeanStd
        - _target_: cropcon.engine.data_preprocessor.BandPadding

val:
    _target_: cropcon.engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
        - _target_: cropcon.engine.data_preprocessor.ResizeToEncoder
        - _target_: cropcon.engine.data_preprocessor.BandFilter
        - _target_: cropcon.engine.data_preprocessor.NormalizeMeanStd
        - _target_: cropcon.engine.data_preprocessor.BandPadding

test:
    _target_: cropcon.engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
        - _target_: cropcon.engine.data_preprocessor.ResizeToEncoder
        - _target_: cropcon.engine.data_preprocessor.BandFilter
        - _target_: cropcon.engine.data_preprocessor.NormalizeMeanStd
        - _target_: cropcon.engine.data_preprocessor.BandPadding
