_target_: cropcon.datasets.horticola.CropsChileHorticola
dataset_name: CropsChileHorticola
root_path: /data/nisla/ChileCrops_horticola/
download_url: null
auto_download: False

img_size: 128
multi_temporal: 69
multi_modal: False


fold_config: null
support_test: True

# classes
ignore_index: 0
num_classes: 31
classes:
  - Background
  - ACELGA
  - BETARRAGA
  - BROCOLI
  - CEBOLLA
  - CEBOLLA TEMPRANA
  - CEBOLLIN
  - CHOCLO
  - CILANTRO
  - COLIFLOR
  - ESPINACA
  - FRUTILLA
  - LECHUGA
  - MELON
  - PAPA
  - PIMIENTO
  - POROTO GRANADO
  - POROTO VERDE
  - RADICCIO
  - SAND�A
  - TOMATE CONSUMO FRESCO
  - TOMATE INDUSTRIAL
  - ZAPALLO GUARDA
  - ZAPALLO ITALIANO
  - AJI
  - AJO
  - CEBOLLA DE GUARDA
  - CEBOLLA INTERMEDIA O PASCUALINA
  - PEPINO DE ENSALADA
  - REPOLLO
  - ZAPALLO TEMPRANO
  
distribution:
  - 0.941676
  - 0.000186
  - 0.000491
  - 0.000793
  - 0.001520
  - 0.000404
  - 0.000545
  - 0.006690
  - 0.000332
  - 0.000601
  - 0.000332
  - 0.001198
  - 0.000885
  - 0.003523
  - 0.004401
  - 0.000500
  - 0.001998
  - 0.000674
  - 0.000002
  - 0.001984
  - 0.003939
  - 0.011209
  - 0.007166
  - 0.000772
  - 0.000246
  - 0.002661
  - 0.004042
  - 0.000370
  - 0.000057
  - 0.000716
  - 0.000088

bands:
  optical:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8A
    - B9
    - B11
    - B12

  elevation:
    - elevation
  mTPI:
    - mTPI
  landforms:
    - landforms

data_mean:
  optical:
    - 4167.4197
    - 4057.2493
    - 4124.6608
    - 4155.8101
    - 4488.8895
    - 4940.0963
    - 5112.4936
    - 5304.6655
    - 5944.9768
    - 3639.6654
    - 3170.4272
    - 5226.6731
  elevation:
    - 0.0114183
  mTPI:
    - 4.252e-08
  landforms:
    - 0.1153389

data_std:
  optical:
    - 4167.4197
    - 4057.2493
    - 4124.6608
    - 4155.8101
    - 4488.8895
    - 4940.0963
    - 5112.4936
    - 5304.6655
    - 5944.9768
    - 3639.6654
    - 3170.4272
    - 5226.6731
  elevation:
    - 0.0020201
  mTPI:
    - 3.974e-05
  landforms:
    - 0.0310551


data_min:
  optical:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  elevation:
    - 0.0039368877
  mTPI:
    - -2.188608e-08
  landforms:
    - 0.0470588244

data_max:
  optical:
    - 22484.0
    - 19216.0
    - 19808.0
    - 18368.0
    - 18027.0
    - 17871.0
    - 17708.0
    - 17072.0
    - 17727.0
    - 16133.0
    - 16070.0
    - 17440.0
  elevation:
    - 0.0167546626
  mTPI:
    - 2.142042e-08
  landforms:
    - 0.1647058874