trainer:
  _target_: cropcon.engine.pretrainer.Trainer
  # params overwritten in run
  model: null
  train_loader: null
  optimizer: null
  lr_scheduler: null
  evaluator: null
  exp_dir: null
  device: null
  criterion: null

  # params to adapt
  n_epochs: 80
  precision: fp32
  ckpt_interval: 1000
  eval_interval: 1
  log_interval: 10
  use_wandb: ${use_wandb}
  tau: 0.1
  alpha: 0.0


