_target_:  cropcon.encoders.convnextV2.ConvNext
encoder_weights: null
download_url: null
input_size: ${dataset.img_size}
multi_temporal: ${dataset.multi_temporal}
topology: [96, 192, 384, 768]

input_bands: ${dataset.bands}

output_dim:
  - 96
  - 192
  - 384
  - 768

