_target_:  cropcon.encoders.convnext.ConvNext
encoder_weights: null
download_url: null
input_size: ${dataset.img_size}
multi_temporal: ${dataset.multi_temporal}
topology: [128, 128, 128, 256]

input_bands: ${dataset.bands}

output_dim:
  - 128
  - 128
  - 128
  - 256

